lparameter  tcPathedMasterModel
local lcDSInfo

save datasession to lcDSInfo

select 0
use (psp_addbs(tcPathedMaserModel) + "ddent")
locate for
set textmerge to mmgen_table.prg
set textmerge on

text noshow
* Generated by xctable_import_gen.prg
* Master Model: <<tcPathedMasterModel>>
* <<etos(datetime()>>

lParameters tcDatabase, toTable, tcPathedxCaseModel

if !databaseexists(tcDatabase)
	create database (tcDatabase)
endif

if !dbused(tcDataBase)
	open database (tcDatabase)
endif


llOK = xcTable_import 
	
endtext
set textmerge off
set textmerge to

psp_closealldata(.T.)
restore datasession  from lcDSInfo





